name: gpuc_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0-99.1.beta

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.2
  mt19937: ^0.1.0
  path: ^1.9.0
  grizzly: ^1.0.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

dependency_overrides:
  grizzly:
    path: ../../grizzly/grizzly
